spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5432/orderdb
#    ?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDateTimeCode=false&serverTimezone=Asia/Kolkata
    username: krishnasai
    password: krishnasai

  jpa:
      show-sql: true
      hibernate:
        ddl-auto: create
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect

#  h2:
#    console:
#      enabled: true
#  datasource:
#    url: jdbc:h2:mem:test
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: create

server:
  port: 8083